### ISSUE TITLE
JSON schema validation for model.json

### ISSUE THREAD

**Issue by RohanJahagirdar** [doc-ai/tensorio-android#1]
Create a TIOModelBundleValidator.java file for json schema validation.

**Comment by phildow** [comment]
See https://github.com/doc-ai/tensorio-ios/issues/57

**Comment by phildow** [comment]
Also check out https://github.com/doc-ai/tensorio/tree/schemas/schemas

That PR is still open but includes the latest model schemas (v0.7.0) as well as a number of example model.json files that it validates against. Right now you only need to worry about the tflite schema.

**Comment by RohanJahagirdar** [comment]
Added TIOModelBundleValidator for validation and added the code to IntegrationTests for running the validation for the models in the assets folder. 

The schema for validation is in TFLite folder inside assets.
